/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import {
  members,
  output,
} from './components/interfaces';

declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  Bin as OceBin
} from './components/bin/index';

declare global {
  interface HTMLOceBinElement extends OceBin, HTMLStencilElement {
  }
  var HTMLOceBinElement: {
    prototype: HTMLOceBinElement;
    new (): HTMLOceBinElement;
  };
  interface HTMLElementTagNameMap {
    "oce-bin": HTMLOceBinElement;
  }
  interface ElementTagNameMap {
    "oce-bin": HTMLOceBinElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "oce-bin": JSXElements.OceBinAttributes;
    }
  }
  namespace JSXElements {
    export interface OceBinAttributes extends HTMLAttributes {
      cards?: Array<any>;
      due?: string;
      note?: string;
      outputs?: Array<output>;
      title?: string;
    }
  }
}


import {
  Card as OceCard
} from './components/card/index';

declare global {
  interface HTMLOceCardElement extends OceCard, HTMLStencilElement {
  }
  var HTMLOceCardElement: {
    prototype: HTMLOceCardElement;
    new (): HTMLOceCardElement;
  };
  interface HTMLElementTagNameMap {
    "oce-card": HTMLOceCardElement;
  }
  interface ElementTagNameMap {
    "oce-card": HTMLOceCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "oce-card": JSXElements.OceCardAttributes;
    }
  }
  namespace JSXElements {
    export interface OceCardAttributes extends HTMLAttributes {
      action?: any;
      due?: string;
      members?: Array<members>;
      note?: string;
    }
  }
}


import {
  Kanban as OceKanban
} from './components/kanban/index';

declare global {
  interface HTMLOceKanbanElement extends OceKanban, HTMLStencilElement {
  }
  var HTMLOceKanbanElement: {
    prototype: HTMLOceKanbanElement;
    new (): HTMLOceKanbanElement;
  };
  interface HTMLElementTagNameMap {
    "oce-kanban": HTMLOceKanbanElement;
  }
  interface ElementTagNameMap {
    "oce-kanban": HTMLOceKanbanElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "oce-kanban": JSXElements.OceKanbanAttributes;
    }
  }
  namespace JSXElements {
    export interface OceKanbanAttributes extends HTMLAttributes {
      bins?: string;
      due?: string;
    }
  }
}


import {
  Modal as OceModal
} from './components/modal/index';

declare global {
  interface HTMLOceModalElement extends OceModal, HTMLStencilElement {
  }
  var HTMLOceModalElement: {
    prototype: HTMLOceModalElement;
    new (): HTMLOceModalElement;
  };
  interface HTMLElementTagNameMap {
    "oce-modal": HTMLOceModalElement;
  }
  interface ElementTagNameMap {
    "oce-modal": HTMLOceModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "oce-modal": JSXElements.OceModalAttributes;
    }
  }
  namespace JSXElements {
    export interface OceModalAttributes extends HTMLAttributes {
      data?: any;
    }
  }
}


import {
  Output as OceOutput
} from './components/output/index';

declare global {
  interface HTMLOceOutputElement extends OceOutput, HTMLStencilElement {
  }
  var HTMLOceOutputElement: {
    prototype: HTMLOceOutputElement;
    new (): HTMLOceOutputElement;
  };
  interface HTMLElementTagNameMap {
    "oce-output": HTMLOceOutputElement;
  }
  interface ElementTagNameMap {
    "oce-output": HTMLOceOutputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "oce-output": JSXElements.OceOutputAttributes;
    }
  }
  namespace JSXElements {
    export interface OceOutputAttributes extends HTMLAttributes {
      outputs?: Array<output>;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
